### ISSUE TITLE
EXEC adapter fail to parse executable path with space character

### ISSUE THREAD

**Issue by ttimasdf** [firejox/WinSocat#10]
```powershell
& $winsocat STDIO "EXEC:'C:\Program Files\Wireshark\Wireshark.exe' -k -i -"
```

Error message:

```
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program' with working directory 'C:\Users\user'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at Firejox.App.WinSocat.ProcPiper..ctor(String filename, String arguments) in /_/winsocat/Process.cs:line 59
   at Firejox.App.WinSocat.ProcPiperFactory.NewPiper() in /_/winsocat/Process.cs:line 103
   at Firejox.App.WinSocat.PiperStrategy.ExecuteAsync(IPiperFactory factory, CancellationToken token) in /_/winsocat/IPiperStrategy.cs:line 29
   at Firejox.App.WinSocat.Program.<>c.<<Main>b__0_0>d.MoveNext() in /_/winsocat/Program.cs:line 33
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by firejox** [comment]
This is a bug. I will fix later.
